version: '3'
services:
  mysql_db:
    image: mysql:5.7
    command: --init-file /app/init.sql
    volumes:
      - ./init.sql:/app/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: flink_2021
      MYSQL_USER: flink
      MYSQL_PASSWORD: password
    networks:
      - app-tier

  python_app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql_db
    networks:
      - app-tier
    command:
      tail -f /dev/null

networks:
  app-tier:
    driver: bridge
